# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mbof.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitudeMeters', models.FloatField()),
                ('messageText', models.CharField(max_length=400)),
                ('postingTime', models.DateTimeField(blank=True, editable=False)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('participantCount', models.IntegerField(default=0)),
                ('hashtag', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('loginName', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=50)),
                ('givenName', models.CharField(max_length=50)),
                ('aboutMe', models.CharField(max_length=2000, null=True)),
                ('roles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mbof.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('+1', '+1'), ('-1', '-1'), ('0', '0')], max_length=2)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbof.Message')),
                ('voter', models.ForeignKey(default=mbof.models.currentUserObject, editable=False, on_delete=django.db.models.deletion.CASCADE, to='mbof.User')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(default=mbof.models.currentUserLoginName, editable=False, on_delete=django.db.models.deletion.CASCADE, to='mbof.User'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('message', 'voter')]),
        ),
    ]
