# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='altitude',
            new_name='elevationMeters',
        ),
    ]
