# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0004_message_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='displayName',
            field=models.CharField(default='displayName', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='givenName',
            field=models.CharField(default='givenName', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='surname', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mbof.Role'),
            preserve_default=False,
        ),
    ]
