# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0005_auto_20160223_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='owner',
        ),
    ]
