# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0007_auto_20160223_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('+1', '+1'), ('-1', '-1')], max_length=2)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbof.Message')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbof.User')),
            ],
        ),
    ]
