# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0008_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aboutMe',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='loginName',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
