# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0011_auto_20160303_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='owner',
        ),
    ]
