# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0011_auto_20160303_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbof.User'),
        ),
    ]
