# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0013_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='endTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mbof.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='postingTime',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='startTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
