# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0013_message_owner'),
        ('mbof', '0012_auto_20160303_1519'),
    ]

    operations = [
    ]
