# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0015_auto_20160304_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbof.User'),
        ),
    ]
