# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0016_auto_20160303_1629'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('message', 'voter')]),
        ),
    ]
