# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0018_auto_20160304_0904'),
        ('mbof', '0017_auto_20160303_1634'),
    ]

    operations = [
    ]
