# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mbof.models


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0019_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('+1', '+1'), ('-1', '-1'), ('NA', 'NA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(default=mbof.models.currentUserObject, editable=False, on_delete=django.db.models.deletion.CASCADE, to='mbof.User'),
        ),
    ]
