# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbof', '0020_auto_20160304_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('+1', '+1'), ('-1', '-1'), ('0', '0')], max_length=2),
        ),
    ]
